export const FriendsList = [
  {
    name: '龙鲲博客',
    motto: '这短短的一生，我们最终都会失去。',
    url: 'http://lkblog.net',
    avatar: 'lkblog.net.png',
    color: '#E3D4C1',
  },
  {
    name: '小太',
    motto: '迪士尼在逃公主',
    url: 'https://baka.fun',
    avatar: 'baka.fun.png',
    color: '#E1DAC6',
  },
  {
    name: 'freejishu的美丽世界',
    motto: 'A New World',
    url: 'https://www.freejishu.com',
    avatar: 'www.freejishu.com.png',
    color: '#D1C5BA',
  },
  {
    name: 'Yuhao的小世界',
    motto: '菜且坚',
    url: 'https://blog.yuhaoo.top',
    avatar: 'blog.yuhaoo.top.png',
    color: '#422B1A',
  },
  {
    name: '惊鸿',
    motto: 'code a new world',
    url: 'https://lzyz.fun',
    avatar: 'lzyz.fun.png',
    color: '#696077',
  },
  {
    name: "Troy's Blog",
    motto: 'Troy 的星球',
    url: 'https://itroy.cc',
    avatar: 'itroy.cc.png',
    color: '#0DB3EF',
  },
  {
    name: '提莫酱のBlog',
    motto: '黄粱一梦，山水万重，人间总相逢',
    url: 'https://www.timochan.cn',
    avatar: 'www.timochan.cn.png',
    color: '#E6DCD1',
  },
  {
    name: "YiQike's Blog",
    motto: '世界无限大.且行且珍惜',
    url: 'https://blog.mashiro.us',
    avatar: 'blog.mashiro.us.png',
    color: '#C8D2D7',
  },
  {
    name: 'Unsigned',
    motto: '心如初，不悔梦归处',
    url: 'http://unsignedzhang.cn',
    avatar: 'unsignedzhang.cn.png',
    color: '#E6CDBC',
  },
  {
    name: '渡鸦的小窝',
    motto: '一条快乐咸鱼',
    url: 'https://polarws.moe',
    avatar: 'polarws.moe.png',
    color: '#603C46',
  },
  {
    name: 'ENDsoft',
    motto: '勿忘初心，方得始终',
    url: 'https://r-ay.cn',
    avatar: 'r-ay.cn.png',
    color: '#ECD9DC',
  },
  {
    name: 'Mashiro',
    motto: '樱花庄的白猫',
    url: 'https://2heng.xin',
    avatar: '2heng.xin.png',
    color: '#F1E7D2',
  },
  {
    name: 'luch',
    motto: '全栈进阶之路',
    url: 'https://www.quanzhan.co',
    avatar: 'www.quanzhan.co.png',
    color: '#24343C',
  },
  {
    name: 'Omega',
    motto: '不来海之家聊聊人生吗？',
    url: 'https://www.omega.im',
    avatar: 'www.omega.im.png',
    color: '#E7C3AB',
  },
  {
    name: '藤の青',
    motto: '萌新/伪前端/高中党/弱气后端',
    url: 'https://a632079.me',
    avatar: 'i.a632079.me.png',
    color: '#88B9CA',
  },
  {
    name: 'LWL的自由天空',
    motto: '凛风起，白云涌。',
    url: 'https://blog.lwl12.com',
    avatar: 'blog.lwl12.com.png',
    color: '#FBF4E6',
  },
  {
    name: '律动喵喵的小站',
    motto: '这里是喵喵的个人站点哦QWQ',
    url: 'https://qwq.re',
    avatar: 'qwq.re.png',
    color: '#F3E4D3',
  },
  {
    name: '无涯烟水迷寻',
    motto: '无涯烟水迷寻，暮色沉沉。风花雪月无数，落拓于今。',
    url: 'https://www.wooyaa.art',
    avatar: 'www.wooyaa.art.png',
    color: '#FEFEFE',
  },
  {
    name: 'Lius的无名Blog',
    motto: 'Lius的个人的用来水和用来发布过气优质内容',
    url: 'https://liustogo.cn',
    avatar: 'liustogo.cn.png',
    color: '#A3827A',
  },
  {
    name: 'FGHRSH',
    motto: 'FGHRSH的博客',
    url: 'https://www.fghrsh.net',
    avatar: 'www.fghrsh.net.png',
    color: '#CAE1BE',
  },
  {
    name: '无垠',
    motto: '飞翔的天空无限大',
    url: 'https://flyhigher.top',
    avatar: 'flyhigher.top.png',
    color: '#DBDCD7',
  },
  {
    name: '没有故事的曹同学',
    motto: '不要紧，山野都有雾灯~',
    url: 'http://caotongxue.cn',
    avatar: 'caotongxue.cn.png',
    color: '#121212',
  },
  {
    name: '魔帆博客',
    motto: 'MorFans Lab',
    url: 'https://www.morfans.cn',
    avatar: 'www.morfans.cn.png',
    color: '#F5ECCB',
  },
  {
    name: '夜半观星',
    motto: '我的花园到处是星星的碎片',
    url: 'https://www.ratodo.com',
    avatar: 'www.ratodo.com.png',
    color: '#CCD2D5',
  },
  {
    name: 'DIYgod',
    motto: '写代码是热爱，写到世界充满爱！',
    url: 'https://diygod.me',
    avatar: 'diygod.me.png',
    color: '#F0E3D8',
  },
  {
    name: 'FH云彩博客',
    motto: '以声之色，塑以花之形',
    url: 'https://yuncaioo.com',
    avatar: 'yuncaioo.com.png',
    color: '#6B588A',
  },
  {
    name: 'Ailoli',
    motto: '永远年轻，永远热泪盈眶',
    url: 'https://www.ailoli.org',
    avatar: 'www.ailoli.org.png',
    color: '#44576F',
  },
  {
    name: 'Dragon犬’s blog',
    motto: 'あなたは主人公になりたいですか？',
    url: 'https://blog.furrysp.top',
    avatar: 'blog.furrysp.top.png',
    color: '#7C4C4B',
  },
  {
    name: 'DreamCity',
    motto: '迷惘少年的梦想世界',
    url: 'https://www.littleqiu.net',
    avatar: 'www.littleqiu.net.png',
    color: '#E3BF7D',
  },
  {
    name: 'Mashirl’s Blog',
    motto: '予 世界温柔以待 惟愿 时光静好',
    url: 'https://mashirl.com',
    avatar: 'mashirl.com.png',
    color: '#E2D1D9',
  },
  {
    name: '@typeof',
    motto: '你好，世界！',
    url: 'https://typeof.pw',
    avatar: 'typeof.pw.png',
    color: '#C5CBD4',
  },
  {
    name: '臾离',
    motto: '懒惰的肥宅挖下勤奋的坑',
    url: 'https://blog.xgblack.cn',
    avatar: 'blog.xgblack.cn.png',
    color: '#BBB6CB',
  },
  {
    name: '无用挂件の日记',
    motto: '没有留下什么呢',
    url: 'https://raspii.tech',
    avatar: 'raspii.tech.png',
    color: '#BFC8BF',
  },
  {
    name: '养生元气喵',
    motto: '凡心所向，素履所往',
    url: 'https://www.wutw.site',
    avatar: 'www.wutw.site.png',
    color: '#F2AE2E',
  },
  {
    name: '保罗的小宇宙',
    motto: 'Still single, still lonely.',
    url: 'https://paugram.com',
    avatar: 'paugram.com.png',
    color: '#69595A',
  },
  {
    name: '飞鸟记',
    motto: '记录「技术」与「温度」',
    url: 'https://blog.aflybird.cn/',
    avatar: 'blog.aflybird.cn.png',
    color: '#CCCCDE',
  },
  {
    name: 'Golden Sheep',
    motto: '须知小花的产生,是为了在你的心旁逗留一瞬！',
    url: 'https://www.glodensheep.top/',
    avatar: 'www.glodensheep.top.png',
    color: '#AD393C',
  },
  {
    name: '陆陆侠的生活',
    motto: '安安~这里是陆陆侠的生活',
    url: 'https://llx.life/',
    avatar: 'llx.life.png',
    color: '#F0C0CF',
  },
  {
    name: 'Geek Improve',
    motto: 'JasonSubmara 的个人博客站',
    url: 'https://submara.com/',
    avatar: 'submara.com.png',
    color: '#FFFFFF',
  },
]
